### ISSUE TITLE
Pyramids with negative scale have wrong origin

### ISSUE THREAD

**Issue by macsforme** [JeffM2501/UnityBZWTools#11]
When a pyramid has a negative scale, this editor shows the pyramid as if the origin was the base (the top, in this case). In the client, the origin of a negatively-scaled pyramid is still the point (the bottom, in this case). This results in an inconsistency between what the editor shows and what the client shows.

**Comment by JeffM2501** [comment]
can you please provide a simple sample and screenshots of correct and incorrect behavior so I can test changes?

I just want to make sure that I understand the expectations.

**Comment by macsforme** [comment]
Sure.

The map:

```
World
	name Untitled BZW
	size 400
	flagHeight 0
end

Pyramid
	name NewPyramid_208174115113168368751439274681
	position 0 0 0
	rotation 0
	size 10 10 20
end

Pyramid
	name NewPyramid_208174115113168368751439274681
	position 0 0 20
	rotation 0
	size 10 10 -20
end
```

Appearance in the editor:

![screen shot 2016-12-13 at 5 26 43 pm](https://cloud.githubusercontent.com/assets/4955448/21164914/599b8f96-c159-11e6-8faa-8ed748083782.png)

Appearance in the game:

![screen shot 2016-12-13 at 5 23 34 pm](https://cloud.githubusercontent.com/assets/4955448/21164928/694cd2ec-c159-11e6-8bc4-070d6a3ca070.png)

**Comment by JeffM2501** [comment]
Fixed, will be in Alpha 10
