### ISSUE TITLE
flagHeight setting is not imported from .bzw file

### ISSUE THREAD

**Issue by macsforme** [JeffM2501/UnityBZWTools#12]
You can set the flagHeight for the options block in the editor, and it writes out to the file correctly. However, when you try to import the same file into the editor, flagHeight is always reset to 0.

**Comment by macsforme** [comment]
Sorry, I was importing the wrong file (Unity apparently doesn't remember the name of the file you last used).

**Comment by JeffM2501** [comment]
Yeah, the script handles the import stuff, unity doesn't know you are importing, just that an editor script opened a file open dialog.
