### ISSUE TITLE
Extra elements shouldn't be outputted

### ISSUE THREAD

**Issue by allejo** [JeffM2501/UnityBZWTools#2]
![image](https://cloud.githubusercontent.com/assets/1246453/19953785/516738e2-a12f-11e6-93a5-900d50051285.png)

On output, it shouldn't generate empty `zoneflag` fields. This probably applies to other objects and not just zones

```
Zone
	position 0 0 151
	rotation 0
	size 60 60 0.1
	zoneflag N 2
	zoneflag WG 2
	zoneflag G 1
	zoneflag SW 2
	zoneflag OO 5
	zoneflag
	zoneflag
	zoneflag
	zoneflag
	zoneflag
end
```

**Comment by JeffM2501** [comment]
BzwIO should not longer allow items that require arguments to write empty arguments.
