### ISSUE TITLE
Teleporter link output case sensitive

### ISSUE THREAD

**Issue by allejo** [JeffM2501/UnityBZWTools#3]
I think the BZFS teleporter parsing code may be case-sensitive since it's complaining about the following:

```
Untitled BZW.bzw: warning (line 2332): unknown object parameter "To" - skipping
```

The warnings were gone after I switched it to a lowercase `to`. Additionally, all other objects have lowercase attributes such as "name", "position", etc. So it would seem fitting that links follow this as well.

**Comment by JeffM2501** [comment]
Should be good now, there was some other issues with TPs and links that I fixed too.
