### ISSUE TITLE
Bases shouldn't have some options

### ISSUE THREAD

**Issue by allejo** [JeffM2501/UnityBZWTools#6]
![image](https://cloud.githubusercontent.com/assets/1246453/20575387/e7640390-b16d-11e6-83c5-709dcf67b1b5.png)

Bases shouldn't have passable, drive through, or shoot through. As for Ricochet, I'm not sure if BZFS supports that

**Comment by JeffM2501** [comment]
They are supported by the data structure and the client will use them if they get set in the version sent over the wire. Even void BaseBuilding::print(std::ostream& out, const std::string& indent) writes them if they are set.

So as far as I see it, if BZFS fails to read them from a text BZW file that's a bug on BZFS's side. They are part of the data structure specification.
