### ISSUE TITLE
Bases aren't textured by default

### ISSUE THREAD

**Issue by allejo** [JeffM2501/UnityBZWTools#7]
![image](https://cloud.githubusercontent.com/assets/1246453/20575462/3951352e-b16e-11e6-8867-ffc63dca85fb.png)

When I create a base through the "Add Base" button in the BZWToolsWindow, the base isn't textured

**Comment by JeffM2501** [comment]
Fixed as part of commit c6cca96c4eb760deda71163e5aa8f1a78b90c41d
