### ISSUE TITLE
Geometry isn't rebuilt when base team color is changed

### ISSUE THREAD

**Issue by allejo** [JeffM2501/UnityBZWTools#8]
![image](https://cloud.githubusercontent.com/assets/1246453/20575559/a83e6254-b16e-11e6-906e-d39d73f4d5e3.png)

The display of a base isn't updated when the "Team Color" attribute is changed

**Comment by JeffM2501** [comment]
Fixed in commit c6cca96c4eb760deda71163e5aa8f1a78b90c41d
